import type { KeyDefinition, LayoutType } from "../types";

export const VK = {
  BACKSPACE: 8,
  TAB: 9,
  ENTER: 13,
  SHIFT: 16,
  CTRL: 17,
  ALT: 18,
  PAUSE: 19,
  CAPS_LOCK: 20,
  ESCAPE: 27,
  SPACE: 32,
  PAGE_UP: 33,
  PAGE_DOWN: 34,
  END: 35,
  HOME: 36,
  LEFT: 37,
  UP: 38,
  RIGHT: 39,
  DOWN: 40,
  INSERT: 45,
  DELETE: 46,
  KEY_0: 48,
  KEY_1: 49,
  KEY_2: 50,
  KEY_3: 51,
  KEY_4: 52,
  KEY_5: 53,
  KEY_6: 54,
  KEY_7: 55,
  KEY_8: 56,
  KEY_9: 57,
  KEY_A: 65,
  KEY_B: 66,
  KEY_C: 67,
  KEY_D: 68,
  KEY_E: 69,
  KEY_F: 70,
  KEY_G: 71,
  KEY_H: 72,
  KEY_I: 73,
  KEY_J: 74,
  KEY_K: 75,
  KEY_L: 76,
  KEY_M: 77,
  KEY_N: 78,
  KEY_O: 79,
  KEY_P: 80,
  KEY_Q: 81,
  KEY_R: 82,
  KEY_S: 83,
  KEY_T: 84,
  KEY_U: 85,
  KEY_V: 86,
  KEY_W: 87,
  KEY_X: 88,
  KEY_Y: 89,
  KEY_Z: 90,
  LWIN: 91,
  RWIN: 92,
  APPS: 93,
  NUMPAD0: 96,
  NUMPAD1: 97,
  NUMPAD2: 98,
  NUMPAD3: 99,
  NUMPAD4: 100,
  NUMPAD5: 101,
  NUMPAD6: 102,
  NUMPAD7: 103,
  NUMPAD8: 104,
  NUMPAD9: 105,
  MULTIPLY: 106,
  ADD: 107,
  SEPARATOR: 108,
  SUBTRACT: 109,
  DECIMAL: 110,
  DIVIDE: 111,
  F1: 112,
  F2: 113,
  F3: 114,
  F4: 115,
  F5: 116,
  F6: 117,
  F7: 118,
  F8: 119,
  F9: 120,
  F10: 121,
  F11: 122,
  F12: 123,
  NUMLOCK: 144,
  SCROLL: 145,
  LSHIFT: 160,
  RSHIFT: 161,
  LCTRL: 162,
  RCTRL: 163,
  LALT: 164,
  RALT: 165,
  OEM_1: 186, // : (JIS)
  OEM_PLUS: 187, // ; (JIS)
  OEM_COMMA: 188, // ,
  OEM_MINUS: 189, // -
  OEM_PERIOD: 190, // .
  OEM_2: 191, // /
  OEM_3: 192, // @ (JIS)
  OEM_4: 219, // [
  OEM_5: 220, // \ (Yen)
  OEM_6: 221, // ]
  OEM_7: 222, // ^ (JIS)
  OEM_8: 223,
  OEM_102: 226, // \ (Backslash, Ro)
  KANA: 242,
  KANJI: 244,
  CONVERT: 245,
  NONCONVERT: 246,
} as const;

export const KEY_SIZE_REM = 3;

const KEYBOARD_LAYOUT_US: KeyDefinition[][] = [
  [
    { label: "Esc", vk: VK.ESCAPE },
    { label: "F1", vk: VK.F1 },
    { label: "F2", vk: VK.F2 },
    { label: "F3", vk: VK.F3 },
    { label: "F4", vk: VK.F4 },
    { label: "F5", vk: VK.F5 },
    { label: "F6", vk: VK.F6 },
    { label: "F7", vk: VK.F7 },
    { label: "F8", vk: VK.F8 },
    { label: "F9", vk: VK.F9 },
    { label: "F10", vk: VK.F10 },
    { label: "F11", vk: VK.F11 },
    { label: "F12", vk: VK.F12 },
  ],
  [
    { label: "`", vk: VK.OEM_3 },
    { label: "1", vk: VK.KEY_1 },
    { label: "2", vk: VK.KEY_2 },
    { label: "3", vk: VK.KEY_3 },
    { label: "4", vk: VK.KEY_4 },
    { label: "5", vk: VK.KEY_5 },
    { label: "6", vk: VK.KEY_6 },
    { label: "7", vk: VK.KEY_7 },
    { label: "8", vk: VK.KEY_8 },
    { label: "9", vk: VK.KEY_9 },
    { label: "0", vk: VK.KEY_0 },
    { label: "-", vk: VK.OEM_MINUS },
    { label: "=", vk: VK.OEM_PLUS },
    { label: "Back", vk: VK.BACKSPACE, width: 2 },
  ],
  [
    { label: "Tab", vk: VK.TAB, width: 1.5 },
    { label: "Q", vk: VK.KEY_Q },
    { label: "W", vk: VK.KEY_W },
    { label: "E", vk: VK.KEY_E },
    { label: "R", vk: VK.KEY_R },
    { label: "T", vk: VK.KEY_T },
    { label: "Y", vk: VK.KEY_Y },
    { label: "U", vk: VK.KEY_U },
    { label: "I", vk: VK.KEY_I },
    { label: "O", vk: VK.KEY_O },
    { label: "P", vk: VK.KEY_P },
    { label: "[", vk: VK.OEM_4 },
    { label: "]", vk: VK.OEM_6 },
    { label: "\\", vk: VK.OEM_5, width: 1.5 },
  ],
  [
    { label: "Caps", vk: VK.CAPS_LOCK, width: 1.8 },
    { label: "A", vk: VK.KEY_A },
    { label: "S", vk: VK.KEY_S },
    { label: "D", vk: VK.KEY_D },
    { label: "F", vk: VK.KEY_F },
    { label: "G", vk: VK.KEY_G },
    { label: "H", vk: VK.KEY_H },
    { label: "J", vk: VK.KEY_J },
    { label: "K", vk: VK.KEY_K },
    { label: "L", vk: VK.KEY_L },
    { label: ";", vk: VK.OEM_1 },
    { label: "'", vk: VK.OEM_7 },
    { label: "Enter", vk: VK.ENTER, width: 2.2 },
  ],
  [
    { label: "Shift", vk: VK.LSHIFT, width: 2.4 },
    { label: "Z", vk: VK.KEY_Z },
    { label: "X", vk: VK.KEY_X },
    { label: "C", vk: VK.KEY_C },
    { label: "V", vk: VK.KEY_V },
    { label: "B", vk: VK.KEY_B },
    { label: "N", vk: VK.KEY_N },
    { label: "M", vk: VK.KEY_M },
    { label: ",", vk: VK.OEM_COMMA },
    { label: ".", vk: VK.OEM_PERIOD },
    { label: "/", vk: VK.OEM_2 },
    { label: "Shift", vk: VK.RSHIFT, width: 2.6 },
  ],
  [
    { label: "Ctrl", vk: VK.LCTRL, width: 1.5 },
    { label: "Win", vk: VK.LWIN, width: 1.5 },
    { label: "Alt", vk: VK.LALT, width: 1.5 },
    { label: "Space", vk: VK.SPACE, width: 6 },
    { label: "Alt", vk: VK.RALT, width: 1.5 },
    { label: "Win", vk: VK.RWIN, width: 1.5 },
    { label: "Ctrl", vk: VK.RCTRL, width: 1.5 },
  ],
];

const KEYBOARD_LAYOUT_JIS: KeyDefinition[][] = [
  [
    { label: "Esc", vk: VK.ESCAPE },
    { label: "F1", vk: VK.F1 },
    { label: "F2", vk: VK.F2 },
    { label: "F3", vk: VK.F3 },
    { label: "F4", vk: VK.F4 },
    { label: "F5", vk: VK.F5 },
    { label: "F6", vk: VK.F6 },
    { label: "F7", vk: VK.F7 },
    { label: "F8", vk: VK.F8 },
    { label: "F9", vk: VK.F9 },
    { label: "F10", vk: VK.F10 },
    { label: "F11", vk: VK.F11 },
    { label: "F12", vk: VK.F12 },
  ],
  [
    { label: "半/全", vk: VK.KANJI },
    { label: "1", vk: VK.KEY_1 },
    { label: "2", vk: VK.KEY_2 },
    { label: "3", vk: VK.KEY_3 },
    { label: "4", vk: VK.KEY_4 },
    { label: "5", vk: VK.KEY_5 },
    { label: "6", vk: VK.KEY_6 },
    { label: "7", vk: VK.KEY_7 },
    { label: "8", vk: VK.KEY_8 },
    { label: "9", vk: VK.KEY_9 },
    { label: "0", vk: VK.KEY_0 },
    { label: "-", vk: VK.OEM_MINUS },
    { label: "^", vk: VK.OEM_7 },
    { label: "¥", vk: VK.OEM_5 },
    { label: "BS", vk: VK.BACKSPACE },
  ],
  [
    { label: "Tab", vk: VK.TAB, width: 1.5 },
    { label: "Q", vk: VK.KEY_Q },
    { label: "W", vk: VK.KEY_W },
    { label: "E", vk: VK.KEY_E },
    { label: "R", vk: VK.KEY_R },
    { label: "T", vk: VK.KEY_T },
    { label: "Y", vk: VK.KEY_Y },
    { label: "U", vk: VK.KEY_U },
    { label: "I", vk: VK.KEY_I },
    { label: "O", vk: VK.KEY_O },
    { label: "P", vk: VK.KEY_P },
    { label: "@", vk: VK.OEM_3 },
    { label: "[", vk: VK.OEM_4 },
    { label: "Enter", vk: VK.ENTER, width: 1.5 },
  ],
  [
    { label: "Caps", vk: VK.CAPS_LOCK, width: 1.8 },
    { label: "A", vk: VK.KEY_A },
    { label: "S", vk: VK.KEY_S },
    { label: "D", vk: VK.KEY_D },
    { label: "F", vk: VK.KEY_F },
    { label: "G", vk: VK.KEY_G },
    { label: "H", vk: VK.KEY_H },
    { label: "J", vk: VK.KEY_J },
    { label: "K", vk: VK.KEY_K },
    { label: "L", vk: VK.KEY_L },
    { label: ";", vk: VK.OEM_PLUS },
    { label: ":", vk: VK.OEM_1 },
    { label: "]", vk: VK.OEM_6 },
    { label: "", vk: VK.ENTER },
  ],
  [
    { label: "Shift", vk: VK.LSHIFT, width: 2.3 },
    { label: "Z", vk: VK.KEY_Z },
    { label: "X", vk: VK.KEY_X },
    { label: "C", vk: VK.KEY_C },
    { label: "V", vk: VK.KEY_V },
    { label: "B", vk: VK.KEY_B },
    { label: "N", vk: VK.KEY_N },
    { label: "M", vk: VK.KEY_M },
    { label: ",", vk: VK.OEM_COMMA },
    { label: ".", vk: VK.OEM_PERIOD },
    { label: "/", vk: VK.OEM_2 },
    { label: "\\", vk: VK.OEM_102 },
    { label: "Shift", vk: VK.RSHIFT, width: 1.5 },
  ],
  [
    { label: "Ctrl", vk: VK.LCTRL, width: 1.5 },
    { label: "Win", vk: VK.LWIN, width: 1.2 },
    { label: "Alt", vk: VK.LALT, width: 1.2 },
    { label: "無変換", vk: VK.NONCONVERT, width: 1.5 },
    { label: "Space", vk: VK.SPACE, width: 3.5 },
    { label: "変換", vk: VK.CONVERT, width: 1.5 },
    { label: "かな", vk: VK.KANA, width: 1.5 },
    { label: "Alt", vk: VK.RALT, width: 1.2 },
    { label: "App", vk: VK.APPS, width: 1.2 },
    { label: "Ctrl", vk: VK.RCTRL, width: 1.5 },
  ],
];

export const KEYBOARD_LAYOUT = {
  JIS: KEYBOARD_LAYOUT_JIS,
  US: KEYBOARD_LAYOUT_US,
} as const satisfies Record<LayoutType, KeyDefinition[][]>;

export const SWITCH_LAYOUT_RULE = {
  JIS: "US",
  US: "JIS",
} as const;
