import type { KeyDefinition } from "../types";
import { VK } from "./vk";

export const KEYBOARD_LAYOUT_US: KeyDefinition[][] = [
  [
    { label: "Esc", vk: VK.ESCAPE },
    { label: "F1", vk: VK.F1 },
    { label: "F2", vk: VK.F2 },
    { label: "F3", vk: VK.F3 },
    { label: "F4", vk: VK.F4 },
    { label: "F5", vk: VK.F5 },
    { label: "F6", vk: VK.F6 },
    { label: "F7", vk: VK.F7 },
    { label: "F8", vk: VK.F8 },
    { label: "F9", vk: VK.F9 },
    { label: "F10", vk: VK.F10 },
    { label: "F11", vk: VK.F11 },
    { label: "F12", vk: VK.F12 },
  ],
  [
    { label: "`", vk: VK.OEM_3 },
    { label: "1", vk: VK.KEY_1 },
    { label: "2", vk: VK.KEY_2 },
    { label: "3", vk: VK.KEY_3 },
    { label: "4", vk: VK.KEY_4 },
    { label: "5", vk: VK.KEY_5 },
    { label: "6", vk: VK.KEY_6 },
    { label: "7", vk: VK.KEY_7 },
    { label: "8", vk: VK.KEY_8 },
    { label: "9", vk: VK.KEY_9 },
    { label: "0", vk: VK.KEY_0 },
    { label: "-", vk: VK.OEM_MINUS },
    { label: "=", vk: VK.OEM_PLUS },
    { label: "Back", vk: VK.BACKSPACE, width: 2 },
  ],
  [
    { label: "Tab", vk: VK.TAB, width: 1.5 },
    { label: "Q", vk: VK.KEY_Q },
    { label: "W", vk: VK.KEY_W },
    { label: "E", vk: VK.KEY_E },
    { label: "R", vk: VK.KEY_R },
    { label: "T", vk: VK.KEY_T },
    { label: "Y", vk: VK.KEY_Y },
    { label: "U", vk: VK.KEY_U },
    { label: "I", vk: VK.KEY_I },
    { label: "O", vk: VK.KEY_O },
    { label: "P", vk: VK.KEY_P },
    { label: "[", vk: VK.OEM_4 },
    { label: "]", vk: VK.OEM_6 },
    { label: "\\", vk: VK.OEM_5, width: 1.5 },
  ],
  [
    { label: "Caps", vk: VK.CAPS_LOCK, width: 1.8 },
    { label: "A", vk: VK.KEY_A },
    { label: "S", vk: VK.KEY_S },
    { label: "D", vk: VK.KEY_D },
    { label: "F", vk: VK.KEY_F },
    { label: "G", vk: VK.KEY_G },
    { label: "H", vk: VK.KEY_H },
    { label: "J", vk: VK.KEY_J },
    { label: "K", vk: VK.KEY_K },
    { label: "L", vk: VK.KEY_L },
    { label: ";", vk: VK.OEM_1 },
    { label: "'", vk: VK.OEM_7 },
    { label: "Enter", vk: VK.ENTER, width: 2.2 },
  ],
  [
    { label: "Shift", vk: VK.LSHIFT, width: 2.4 },
    { label: "Z", vk: VK.KEY_Z },
    { label: "X", vk: VK.KEY_X },
    { label: "C", vk: VK.KEY_C },
    { label: "V", vk: VK.KEY_V },
    { label: "B", vk: VK.KEY_B },
    { label: "N", vk: VK.KEY_N },
    { label: "M", vk: VK.KEY_M },
    { label: ",", vk: VK.OEM_COMMA },
    { label: ".", vk: VK.OEM_PERIOD },
    { label: "/", vk: VK.OEM_2 },
    { label: "Shift", vk: VK.RSHIFT, width: 2.6 },
  ],
  [
    { label: "Ctrl", vk: VK.LCTRL, width: 1.5 },
    { label: "Win", vk: VK.LWIN, width: 1.5 },
    { label: "Alt", vk: VK.LALT, width: 1.5 },
    { label: "Space", vk: VK.SPACE, width: 6 },
    { label: "Alt", vk: VK.RALT, width: 1.5 },
    { label: "Win", vk: VK.RWIN, width: 1.5 },
    { label: "Ctrl", vk: VK.RCTRL, width: 1.5 },
  ],
];
