import type { KeyboardLayout } from "../types";
import { VK } from "./vk";

export const KEYBOARD_LAYOUT_JIS: KeyboardLayout = [
  {
    id: 1,
    row: [
      { id: 1, label: "Esc", vk: VK.ESCAPE },
      { id: 2, label: "F1", vk: VK.F1 },
      { id: 3, label: "F2", vk: VK.F2 },
      { id: 4, label: "F3", vk: VK.F3 },
      { id: 5, label: "F4", vk: VK.F4 },
      { id: 6, label: "F5", vk: VK.F5 },
      { id: 7, label: "F6", vk: VK.F6 },
      { id: 8, label: "F7", vk: VK.F7 },
      { id: 9, label: "F8", vk: VK.F8 },
      { id: 10, label: "F9", vk: VK.F9 },
      { id: 11, label: "F10", vk: VK.F10 },
      { id: 12, label: "F11", vk: VK.F11 },
      { id: 13, label: "F12", vk: VK.F12 },
      { id: 14, label: "Delete", vk: VK.DELETE },
    ],
  },
  {
    id: 2,
    row: [
      { id: 15, label: "半/全", vk: VK.KANJI },
      { id: 16, label: "1", vk: VK.KEY_1 },
      { id: 17, label: "2", vk: VK.KEY_2 },
      { id: 18, label: "3", vk: VK.KEY_3 },
      { id: 19, label: "4", vk: VK.KEY_4 },
      { id: 20, label: "5", vk: VK.KEY_5 },
      { id: 21, label: "6", vk: VK.KEY_6 },
      { id: 22, label: "7", vk: VK.KEY_7 },
      { id: 23, label: "8", vk: VK.KEY_8 },
      { id: 24, label: "9", vk: VK.KEY_9 },
      { id: 25, label: "0", vk: VK.KEY_0 },
      { id: 26, label: "-", vk: VK.OEM_MINUS },
      { id: 27, label: "^", vk: VK.OEM_7 },
      { id: 28, label: "¥", vk: VK.OEM_5 },
      { id: 29, label: "BS", vk: VK.BACKSPACE },
    ],
  },
  {
    id: 3,
    row: [
      { id: 30, label: "Tab", vk: VK.TAB, width: 1.5 },
      { id: 31, label: "q", vk: VK.KEY_Q },
      { id: 32, label: "w", vk: VK.KEY_W },
      { id: 33, label: "e", vk: VK.KEY_E },
      { id: 34, label: "r", vk: VK.KEY_R },
      { id: 35, label: "t", vk: VK.KEY_T },
      { id: 36, label: "y", vk: VK.KEY_Y },
      { id: 37, label: "u", vk: VK.KEY_U },
      { id: 38, label: "i", vk: VK.KEY_I },
      { id: 39, label: "o", vk: VK.KEY_O },
      { id: 40, label: "p", vk: VK.KEY_P },
      { id: 41, label: "@", vk: VK.OEM_3 },
      { id: 42, label: "[", vk: VK.OEM_4 },
      { id: 43, label: "Enter", vk: VK.ENTER, width: 1.5 },
    ],
  },
  {
    id: 4,
    row: [
      { id: 44, label: "Caps", vk: VK.CAPS_LOCK, width: 1.8 },
      { id: 45, label: "a", vk: VK.KEY_A },
      { id: 46, label: "s", vk: VK.KEY_S },
      { id: 47, label: "d", vk: VK.KEY_D },
      { id: 48, label: "f", vk: VK.KEY_F },
      { id: 49, label: "g", vk: VK.KEY_G },
      { id: 50, label: "h", vk: VK.KEY_H },
      { id: 51, label: "j", vk: VK.KEY_J },
      { id: 52, label: "k", vk: VK.KEY_K },
      { id: 53, label: "l", vk: VK.KEY_L },
      { id: 54, label: ";", vk: VK.OEM_PLUS },
      { id: 55, label: ":", vk: VK.OEM_1 },
      { id: 56, label: "]", vk: VK.OEM_6 },
      { id: 57, label: "", vk: VK.ENTER },
    ],
  },
  {
    id: 5,
    row: [
      { id: 58, label: "Shift", vk: VK.LSHIFT, width: 2.3 },
      { id: 59, label: "z", vk: VK.KEY_Z },
      { id: 60, label: "x", vk: VK.KEY_X },
      { id: 61, label: "c", vk: VK.KEY_C },
      { id: 62, label: "v", vk: VK.KEY_V },
      { id: 63, label: "b", vk: VK.KEY_B },
      { id: 64, label: "n", vk: VK.KEY_N },
      { id: 65, label: "m", vk: VK.KEY_M },
      { id: 66, label: ",", vk: VK.OEM_COMMA },
      { id: 67, label: ".", vk: VK.OEM_PERIOD },
      { id: 68, label: "/", vk: VK.OEM_2 },
      { id: 69, label: "\\", vk: VK.OEM_102 },
      { id: 70, label: "Shift", vk: VK.RSHIFT, width: 1.5 },
    ],
  },
  {
    id: 6,
    row: [
      { id: 71, label: "Ctrl", vk: VK.LCTRL, width: 1.5 },
      { id: 72, label: "Win", vk: VK.LWIN, width: 1.2 },
      { id: 73, label: "Alt", vk: VK.LALT, width: 1.2 },
      { id: 74, label: "無変換", vk: VK.NONCONVERT, width: 1.5 },
      { id: 75, label: "Space", vk: VK.SPACE, width: 3.5 },
      { id: 76, label: "変換", vk: VK.CONVERT, width: 1.5 },
      { id: 77, label: "かな", vk: VK.KANA, width: 1.5 },
      { id: 78, label: "Alt", vk: VK.RALT, width: 1.2 },
      { id: 79, label: "App", vk: VK.APPS, width: 1.2 },
      { id: 80, label: "Ctrl", vk: VK.RCTRL, width: 1.5 },
    ],
  },
];

export const KEYBOARD_LAYOUT_JIS_SHIFT: KeyboardLayout = [
  {
    id: 1,
    row: [
      { id: 81, label: "Esc", vk: VK.ESCAPE },
      { id: 82, label: "F1", vk: VK.F1 },
      { id: 83, label: "F2", vk: VK.F2 },
      { id: 84, label: "F3", vk: VK.F3 },
      { id: 85, label: "F4", vk: VK.F4 },
      { id: 86, label: "F5", vk: VK.F5 },
      { id: 87, label: "F6", vk: VK.F6 },
      { id: 88, label: "F7", vk: VK.F7 },
      { id: 89, label: "F8", vk: VK.F8 },
      { id: 90, label: "F9", vk: VK.F9 },
      { id: 91, label: "F10", vk: VK.F10 },
      { id: 92, label: "F11", vk: VK.F11 },
      { id: 93, label: "F12", vk: VK.F12 },
      { id: 94, label: "Delete", vk: VK.DELETE },
    ],
  },
  {
    id: 2,
    row: [
      { id: 95, label: "半/全", vk: VK.KANJI },
      { id: 96, label: "!", vk: [VK.KEY_1, VK.LSHIFT] },
      { id: 97, label: "@", vk: [VK.KEY_2, VK.LSHIFT] },
      { id: 98, label: "#", vk: [VK.KEY_3, VK.LSHIFT] },
      { id: 99, label: "$", vk: [VK.KEY_4, VK.LSHIFT] },
      { id: 100, label: "%", vk: [VK.KEY_5, VK.LSHIFT] },
      { id: 101, label: "^", vk: [VK.KEY_6, VK.LSHIFT] },
      { id: 102, label: "&", vk: [VK.KEY_7, VK.LSHIFT] },
      { id: 103, label: "*", vk: [VK.KEY_8, VK.LSHIFT] },
      { id: 104, label: "(", vk: [VK.KEY_9, VK.LSHIFT] },
      { id: 105, label: ")", vk: [VK.KEY_0, VK.LSHIFT] },
      { id: 106, label: "=", vk: [VK.OEM_MINUS, VK.LSHIFT] },
      { id: 107, label: "+", vk: [VK.OEM_7, VK.LSHIFT] },
      { id: 108, label: "|", vk: [VK.OEM_5, VK.LSHIFT] },
      { id: 109, label: "BS", vk: VK.BACKSPACE },
    ],
  },
  {
    id: 3,
    row: [
      { id: 110, label: "Tab", vk: VK.TAB, width: 1.5 },
      { id: 111, label: "Q", vk: [VK.KEY_Q, VK.LSHIFT] },
      { id: 112, label: "W", vk: [VK.KEY_W, VK.LSHIFT] },
      { id: 113, label: "E", vk: [VK.KEY_E, VK.LSHIFT] },
      { id: 114, label: "R", vk: [VK.KEY_R, VK.LSHIFT] },
      { id: 115, label: "T", vk: [VK.KEY_T, VK.LSHIFT] },
      { id: 116, label: "Y", vk: [VK.KEY_Y, VK.LSHIFT] },
      { id: 117, label: "U", vk: [VK.KEY_U, VK.LSHIFT] },
      { id: 118, label: "I", vk: [VK.KEY_I, VK.LSHIFT] },
      { id: 119, label: "O", vk: [VK.KEY_O, VK.LSHIFT] },
      { id: 120, label: "P", vk: [VK.KEY_P, VK.LSHIFT] },
      { id: 121, label: "@", vk: [VK.OEM_3, VK.LSHIFT] },
      { id: 122, label: "{", vk: [VK.OEM_4, VK.LSHIFT] },
      { id: 123, label: "Enter", vk: VK.ENTER, width: 1.5 },
    ],
  },
  {
    id: 4,
    row: [
      { id: 124, label: "Caps", vk: VK.CAPS_LOCK, width: 1.8 },
      { id: 125, label: "A", vk: [VK.KEY_A, VK.LSHIFT] },
      { id: 126, label: "S", vk: [VK.KEY_S, VK.LSHIFT] },
      { id: 127, label: "D", vk: [VK.KEY_D, VK.LSHIFT] },
      { id: 128, label: "F", vk: [VK.KEY_F, VK.LSHIFT] },
      { id: 129, label: "G", vk: [VK.KEY_G, VK.LSHIFT] },
      { id: 130, label: "H", vk: [VK.KEY_H, VK.LSHIFT] },
      { id: 131, label: "J", vk: [VK.KEY_J, VK.LSHIFT] },
      { id: 132, label: "K", vk: [VK.KEY_K, VK.LSHIFT] },
      { id: 133, label: "L", vk: [VK.KEY_L, VK.LSHIFT] },
      { id: 134, label: ":", vk: [VK.OEM_PLUS, VK.LSHIFT] },
      { id: 135, label: "*", vk: [VK.OEM_1, VK.LSHIFT] },
      { id: 136, label: "]", vk: [VK.OEM_6, VK.LSHIFT] },
      { id: 137, label: "", vk: VK.ENTER },
    ],
  },
  {
    id: 5,
    row: [
      { id: 138, label: "Shift", vk: VK.LSHIFT, width: 2.3 },
      { id: 139, label: "Z", vk: [VK.KEY_Z, VK.LSHIFT] },
      { id: 140, label: "X", vk: [VK.KEY_X, VK.LSHIFT] },
      { id: 141, label: "C", vk: [VK.KEY_C, VK.LSHIFT] },
      { id: 142, label: "V", vk: [VK.KEY_V, VK.LSHIFT] },
      { id: 143, label: "B", vk: [VK.KEY_B, VK.LSHIFT] },
      { id: 144, label: "N", vk: [VK.KEY_N, VK.LSHIFT] },
      { id: 145, label: "M", vk: [VK.KEY_M, VK.LSHIFT] },
      { id: 146, label: "<", vk: [VK.OEM_COMMA, VK.LSHIFT] },
      { id: 147, label: ">", vk: [VK.OEM_PERIOD, VK.LSHIFT] },
      { id: 148, label: "?", vk: [VK.OEM_2, VK.LSHIFT] },
      { id: 149, label: "\\", vk: [VK.OEM_102, VK.LSHIFT] },
      { id: 150, label: "Shift", vk: VK.RSHIFT, width: 1.5 },
    ],
  },
  {
    id: 6,
    row: [
      { id: 151, label: "Ctrl", vk: VK.LCTRL, width: 1.5 },
      { id: 152, label: "Win", vk: VK.LWIN, width: 1.2 },
      { id: 153, label: "Alt", vk: VK.LALT, width: 1.2 },
      { id: 154, label: "無変換", vk: VK.NONCONVERT, width: 1.5 },
      { id: 155, label: "Space", vk: VK.SPACE, width: 3.5 },
      { id: 156, label: "変換", vk: VK.CONVERT, width: 1.5 },
      { id: 157, label: "かな", vk: VK.KANA, width: 1.5 },
      { id: 158, label: "Alt", vk: VK.RALT, width: 1.2 },
      { id: 159, label: "App", vk: VK.APPS, width: 1.2 },
      { id: 160, label: "Ctrl", vk: VK.RCTRL, width: 1.5 },
    ],
  },
];

export const KEYBOARD_LAYOUT_JIS_CUSTOM: KeyboardLayout = [
  {
    id: 1,
    row: [
      { id: 161, label: "", vk: 0 },
      { id: 162, label: "", vk: 0 },
      { id: 163, label: "", vk: 0 },
      { id: 164, label: "", vk: 0 },
      { id: 165, label: "", vk: 0 },
      { id: 166, label: "", vk: 0 },
      { id: 167, label: "", vk: 0 },
      { id: 168, label: "", vk: 0 },
      { id: 169, label: "", vk: 0 },
      { id: 170, label: "", vk: 0 },
      { id: 171, label: "", vk: 0 },
      { id: 172, label: "", vk: 0 },
      { id: 173, label: "", vk: 0 },
      { id: 174, label: "", vk: 0 },
    ],
  },
  {
    id: 2,
    row: [
      { id: 175, label: "", vk: 0 },
      { id: 176, label: "", vk: 0 },
      { id: 177, label: "", vk: 0 },
      { id: 178, label: "", vk: 0 },
      { id: 179, label: "", vk: 0 },
      { id: 180, label: "", vk: 0 },
      { id: 181, label: "", vk: 0 },
      { id: 182, label: "", vk: 0 },
      { id: 183, label: "", vk: 0 },
      { id: 184, label: "", vk: 0 },
      { id: 185, label: "", vk: 0 },
      { id: 186, label: "", vk: 0 },
      { id: 187, label: "", vk: 0 },
      { id: 188, label: "", vk: 0 },
    ],
  },
  {
    id: 3,
    row: [
      { id: 189, label: "", vk: 0, width: 1.5 },
      { id: 190, label: "", vk: 0 },
      { id: 191, label: "", vk: 0 },
      { id: 192, label: "", vk: 0 },
      { id: 193, label: "", vk: 0 },
      { id: 194, label: "", vk: 0 },
      { id: 195, label: "", vk: 0 },
      { id: 196, label: "", vk: 0 },
      { id: 197, label: "", vk: 0 },
      { id: 198, label: "", vk: 0 },
      { id: 199, label: "", vk: 0 },
      { id: 200, label: "", vk: 0 },
      { id: 201, label: "", vk: 0, width: 1.5 },
    ],
  },
  {
    id: 4,
    row: [
      { id: 202, label: "", vk: 0, width: 1.8 },
      { id: 203, label: "", vk: 0 },
      { id: 204, label: "", vk: 0 },
      { id: 205, label: "", vk: 0 },
      { id: 206, label: "", vk: 0 },
      { id: 207, label: "", vk: 0 },
      { id: 208, label: "", vk: 0 },
      { id: 209, label: "", vk: 0 },
      { id: 210, label: "", vk: 0 },
      { id: 211, label: "", vk: 0 },
      { id: 212, label: "", vk: 0 },
      { id: 213, label: "", vk: 0 },
      { id: 214, label: "", vk: 0 },
    ],
  },
  {
    id: 5,
    row: [
      { id: 215, label: "", vk: 0, width: 2.3 },
      { id: 216, label: "", vk: 0 },
      { id: 217, label: "", vk: 0 },
      { id: 218, label: "", vk: 0 },
      { id: 219, label: "", vk: 0 },
      { id: 220, label: "", vk: 0 },
      { id: 221, label: "", vk: 0 },
      { id: 222, label: "", vk: 0 },
      { id: 223, label: "", vk: 0 },
      { id: 224, label: "", vk: 0 },
      { id: 225, label: "", vk: 0 },
      { id: 226, label: "", vk: 0 },
    ],
  },
  {
    id: 6,
    row: [
      { id: 227, label: "", vk: 0, width: 1.5 },
      { id: 228, label: "", vk: 0, width: 1.2 },
      { id: 229, label: "", vk: 0, width: 1.2 },
      { id: 230, label: "", vk: 0, width: 1.5 },
      { id: 231, label: "", vk: 0, width: 3.5 },
      { id: 232, label: "", vk: 0, width: 1.5 },
      { id: 233, label: "", vk: 0, width: 1.5 },
      { id: 234, label: "", vk: 0, width: 1.2 },
      { id: 235, label: "", vk: 0, width: 1.2 },
      { id: 236, label: "", vk: 0, width: 1.5 },
    ],
  },
];
